export const FETCH_COLORS = 'FETCH_COLORS';
export const FETCH_MANUFACTURERS = 'FETCH_MANUFACTURERS';
export const FETCH_CAR_LIST = 'FETCH_CAR_LIST';
export const FETCH_CAR_DETAILS = 'FETCH_CAR_DETAILS';
export const SAVE_TO_CART = 'SAVE_TO_CART';
export const SET_FILTERS = 'SET_FILTERS';

const ACTION_TYPES = {
    FETCH_COLORS,
    FETCH_MANUFACTURERS,
    FETCH_CAR_LIST,
    FETCH_CAR_DETAILS,
    SAVE_TO_CART,
    SET_FILTERS,
};

export default ACTION_TYPES